import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

// Flat config (ESLint 9). Full recommended: @eslint/js + typescript-eslint
// recommended (non-type-checked — fast, no project-service needed) +
// react-hooks. The whole point of adopting eslint was react-hooks/
// rules-of-hooks, which would have caught the #357 "fewer hooks than
// expected" crash at build time — that one stays a hard error.
export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      // Generated by @tanstack/router-vite-plugin — not hand-edited.
      "src/routeTree.gen.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.es2021 },
    },
    plugins: { "react-hooks": reactHooks },
    rules: {
      // The gate. rules-of-hooks would have caught the #357 crash at build.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      // TS already errors on undefined identifiers; the base no-undef rule
      // false-positives on TS (worker/DOM globals like `self`) — off per
      // typescript-eslint guidance.
      "no-undef": "off",

      // Pre-existing debt across a previously-unlinted codebase. Rules stay
      // ENABLED (full recommended) but at "warn" so they surface in lint
      // output and burn down incrementally — without blocking CI today.
      // rules-of-hooks above is the only hard error that gates the build.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-irregular-whitespace": "warn",
      "@typescript-eslint/no-unused-expressions": [
        "warn",
        { allowShortCircuit: true, allowTernary: true },
      ],
    },
  },
  {
    // Service worker — runs in ServiceWorkerGlobalScope, so `self` etc. are
    // globals here, not in the browser window scope.
    files: ["public/sw.js"],
    languageOptions: { globals: { ...globals.serviceworker } },
  },
);
