"""Router modules, ordered by original main.py route appearance."""

ROUTER_MODULES = [
    "visits",
    "public",
    "lists",
    "list_items",
    "backlog",
    "habits",
    "metrics",
    "focuses",
    "focus_candidates",
    "todos",
    "items",
    "auth",
    "misc",
    "chat",
    "webhooks",
    "settings",
    "spaces",
    "notes",
    "promises",
    "comments",
    "reactions",
    "uploads",
    "conversations",
    "health",
    "dashboard",
    "tool_calls",
    "mcp",
    "memories",
    "eval",
    "whoop",
    "integrations",
    "capabilities",
    "reflections",
]
