"""baseline schema

Revision ID: ebbf04b84ba5
Revises: 
Create Date: 2026-05-07 02:59:01.864138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbf04b84ba5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claude_usage_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ts', name='uq_claude_usage_turn_session_ts')
    )
    with op.batch_alter_table('claude_usage_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claude_usage_turns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claude_usage_turns_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claude_usage_turns_ts'), ['ts'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('presence_pct', sa.Float(), nullable=True),
    sa.Column('eyes_on_pct', sa.Float(), nullable=True),
    sa.Column('active_pct', sa.Float(), nullable=True),
    sa.Column('engaged_pct', sa.Float(), nullable=True),
    sa.Column('app_focus_pct', sa.Float(), nullable=True),
    sa.Column('focused_apps_input', sa.Text(), nullable=True),
    sa.Column('samples_total', sa.Integer(), nullable=True),
    sa.Column('samples_focused', sa.Integer(), nullable=True),
    sa.Column('hand_to_mouth_count', sa.Integer(), nullable=True),
    sa.Column('phone_in_hand_count', sa.Integer(), nullable=True),
    sa.Column('stand_count', sa.Integer(), nullable=True),
    sa.Column('away_count', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('gooni_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('digest', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gooni_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gooni_snapshots_day'), ['day'], unique=True)

    op.create_table('gooni_takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('take_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'kind', name='uq_gooni_takes_day_kind')
    )
    with op.batch_alter_table('gooni_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gooni_takes_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_gooni_takes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gooni_takes_kind'), ['kind'], unique=False)

    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lists_type'), ['type'], unique=False)

    op.create_table('mcp_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_calls_called_at'), ['called_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_calls_id'), ['id'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('account_email', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('public_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nudge_enabled', sa.Boolean(), nullable=False),
    sa.Column('nudge_hour', sa.Integer(), nullable=False),
    sa.Column('nudge_minute', sa.Integer(), nullable=False),
    sa.Column('nudge_tz', sa.String(), nullable=False),
    sa.Column('nudge_channels', sa.Text(), nullable=False),
    sa.Column('nudge_last_sent_day', sa.String(), nullable=True),
    sa.Column('nudge_last_digests', sa.Text(), nullable=False),
    sa.Column('nudge_prompt', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaces_id'), ['id'], unique=False)

    op.create_table('tracked_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'owner', 'name', name='uq_tracked_repo')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_ip_hash'), ['ip_hash'], unique=False)

    op.create_table('whoop_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recovery_score', sa.Integer(), nullable=True),
    sa.Column('hrv_rmssd_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_performance_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whoop_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whoop_snapshots_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_whoop_snapshots_id'), ['id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('topic_graph', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)

    op.create_table('focus_session_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('app', sa.Text(), nullable=True),
    sa.Column('keys', sa.Integer(), nullable=False),
    sa.Column('mouse', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['focus_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_session_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_session_buckets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_session_buckets_session_id'), ['session_id'], unique=False)

    op.create_table('focus_session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['focus_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_session_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_session_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_session_events_session_id'), ['session_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('suggested_questions', sa.Text(), nullable=True),
    sa.Column('classified_embedding', sa.Text(), nullable=True),
    sa.Column('backlog_note_id', sa.Integer(), nullable=True),
    sa.Column('last_classify_signals', sa.Text(), nullable=True),
    sa.Column('parent_note_id', sa.Integer(), nullable=True),
    sa.Column('excerpt_anchor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backlog_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['parent_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_parent_note_id'), ['parent_note_id'], unique=False)

    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('endgoal', sa.Text(), nullable=True),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('actionable', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scale', sa.String(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('board_status', sa.String(), nullable=True),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_items_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_items_parent_id'), ['parent_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('feedback_for_message_id', sa.Integer(), nullable=True),
    sa.Column('is_feedback', sa.Boolean(), nullable=False),
    sa.Column('trace', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['feedback_for_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    op.create_table('eval_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('start_message_id', sa.Integer(), nullable=False),
    sa.Column('end_message_id', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('eval_status', sa.String(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('overall_comment', sa.Text(), nullable=True),
    sa.Column('dispatched_to_cc_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_note_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['dispatched_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['end_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['start_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_segments_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_segments_eval_status'), ['eval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_segments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_segments_last_message_at'), ['last_message_at'], unique=False)

    op.create_table('focus_todo_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus_item_id', sa.Integer(), nullable=False),
    sa.Column('todo_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['focus_item_id'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['todo_item_id'], ['list_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('focus_item_id', 'todo_item_id', name='uq_focus_todo_link')
    )
    with op.batch_alter_table('focus_todo_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_todo_links_focus_item_id'), ['focus_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_todo_links_todo_item_id'), ['todo_item_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('focus_id', sa.Integer(), nullable=True),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('last_retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['focus_id'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_last_retrieved_at'), ['last_retrieved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_source_note_id'), ['source_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_type'), ['type'], unique=False)

    op.create_table('eval_step_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['eval_segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'step_key', 'step_index', name='uq_eval_step_feedback')
    )
    with op.batch_alter_table('eval_step_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_step_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_step_feedback_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_step_feedback_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_step_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_step_feedback_segment_id'))
        batch_op.drop_index(batch_op.f('ix_eval_step_feedback_message_id'))
        batch_op.drop_index(batch_op.f('ix_eval_step_feedback_id'))

    op.drop_table('eval_step_feedback')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_type'))
        batch_op.drop_index(batch_op.f('ix_memories_source_note_id'))
        batch_op.drop_index(batch_op.f('ix_memories_last_retrieved_at'))
        batch_op.drop_index(batch_op.f('ix_memories_key'))
        batch_op.drop_index(batch_op.f('ix_memories_id'))

    op.drop_table('memories')
    with op.batch_alter_table('focus_todo_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_todo_links_todo_item_id'))
        batch_op.drop_index(batch_op.f('ix_focus_todo_links_focus_item_id'))

    op.drop_table('focus_todo_links')
    with op.batch_alter_table('eval_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_segments_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_eval_segments_id'))
        batch_op.drop_index(batch_op.f('ix_eval_segments_eval_status'))
        batch_op.drop_index(batch_op.f('ix_eval_segments_conversation_id'))

    op.drop_table('eval_segments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_items_parent_id'))
        batch_op.drop_index(batch_op.f('ix_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_list_items_id'))

    op.drop_table('list_items')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_parent_note_id'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    with op.batch_alter_table('focus_session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_session_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_focus_session_events_kind'))
        batch_op.drop_index(batch_op.f('ix_focus_session_events_id'))

    op.drop_table('focus_session_events')
    with op.batch_alter_table('focus_session_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_session_buckets_session_id'))
        batch_op.drop_index(batch_op.f('ix_focus_session_buckets_id'))

    op.drop_table('focus_session_buckets')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('whoop_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whoop_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_whoop_snapshots_date'))

    op.drop_table('whoop_snapshots')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_visits_id'))
        batch_op.drop_index(batch_op.f('ix_visits_created_at'))

    op.drop_table('visits')
    op.drop_table('tracked_repos')
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaces_id'))

    op.drop_table('spaces')
    op.drop_table('settings')
    op.drop_table('public_profile')
    op.drop_table('oauth_tokens')
    with op.batch_alter_table('mcp_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_calls_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_calls_called_at'))

    op.drop_table('mcp_calls')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_type'))
        batch_op.drop_index(batch_op.f('ix_lists_id'))

    op.drop_table('lists')
    with op.batch_alter_table('gooni_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gooni_takes_kind'))
        batch_op.drop_index(batch_op.f('ix_gooni_takes_id'))
        batch_op.drop_index(batch_op.f('ix_gooni_takes_day'))

    op.drop_table('gooni_takes')
    with op.batch_alter_table('gooni_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gooni_snapshots_day'))

    op.drop_table('gooni_snapshots')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_id'))

    op.drop_table('focus_sessions')
    with op.batch_alter_table('claude_usage_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claude_usage_turns_ts'))
        batch_op.drop_index(batch_op.f('ix_claude_usage_turns_session_id'))
        batch_op.drop_index(batch_op.f('ix_claude_usage_turns_id'))

    op.drop_table('claude_usage_turns')
    # ### end Alembic commands ###
