/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/public'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CreativeRouteImport } from './routes/creative'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicIndexRouteImport } from './routes/public.index'
import { Route as PublicMcpRouteImport } from './routes/public.mcp'
import { Route as PublicCvRouteImport } from './routes/public.cv'
import { Route as PublicNoteIdRouteImport } from './routes/public.$noteId'

const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeRoute = CreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMcpRoute = PublicMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCvRoute = PublicCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNoteIdRoute = PublicNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creative': typeof CreativeRoute
  '/focus': typeof FocusRoute
  '/home': typeof HomeRoute
  '/memories': typeof MemoriesRoute
  '/public': typeof PublicRouteWithChildren
  '/public/$noteId': typeof PublicNoteIdRoute
  '/public/cv': typeof PublicCvRoute
  '/public/mcp': typeof PublicMcpRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creative': typeof CreativeRoute
  '/focus': typeof FocusRoute
  '/home': typeof HomeRoute
  '/memories': typeof MemoriesRoute
  '/public/$noteId': typeof PublicNoteIdRoute
  '/public/cv': typeof PublicCvRoute
  '/public/mcp': typeof PublicMcpRoute
  '/public': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creative': typeof CreativeRoute
  '/focus': typeof FocusRoute
  '/home': typeof HomeRoute
  '/memories': typeof MemoriesRoute
  '/public': typeof PublicRouteWithChildren
  '/public/$noteId': typeof PublicNoteIdRoute
  '/public/cv': typeof PublicCvRoute
  '/public/mcp': typeof PublicMcpRoute
  '/public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creative'
    | '/focus'
    | '/home'
    | '/memories'
    | '/public'
    | '/public/$noteId'
    | '/public/cv'
    | '/public/mcp'
    | '/public/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creative'
    | '/focus'
    | '/home'
    | '/memories'
    | '/public/$noteId'
    | '/public/cv'
    | '/public/mcp'
    | '/public'
  id:
    | '__root__'
    | '/'
    | '/creative'
    | '/focus'
    | '/home'
    | '/memories'
    | '/public'
    | '/public/$noteId'
    | '/public/cv'
    | '/public/mcp'
    | '/public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreativeRoute: typeof CreativeRoute
  FocusRoute: typeof FocusRoute
  HomeRoute: typeof HomeRoute
  MemoriesRoute: typeof MemoriesRoute
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative': {
      id: '/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof CreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/mcp': {
      id: '/public/mcp'
      path: '/mcp'
      fullPath: '/public/mcp'
      preLoaderRoute: typeof PublicMcpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/cv': {
      id: '/public/cv'
      path: '/cv'
      fullPath: '/public/cv'
      preLoaderRoute: typeof PublicCvRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/$noteId': {
      id: '/public/$noteId'
      path: '/$noteId'
      fullPath: '/public/$noteId'
      preLoaderRoute: typeof PublicNoteIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicNoteIdRoute: typeof PublicNoteIdRoute
  PublicCvRoute: typeof PublicCvRoute
  PublicMcpRoute: typeof PublicMcpRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicNoteIdRoute: PublicNoteIdRoute,
  PublicCvRoute: PublicCvRoute,
  PublicMcpRoute: PublicMcpRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreativeRoute: CreativeRoute,
  FocusRoute: FocusRoute,
  HomeRoute: HomeRoute,
  MemoriesRoute: MemoriesRoute,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
